version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install for static HTML"

  pre_build:
    commands:
      - echo "Pre-build phase skipped"

  build:
    commands:
      - echo "Build phase skipped (static HTML only)"

  post_build:
    commands:
      - echo "Packaging static HTML files for deployment"

artifacts:
  files:
    - '**/*'
